version: '3.9'

services:
  db:
    container_name: testing-database
    image: mysql:8
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: tests
