export const RealmMap = {
  Lightbringer: 'lightbringer',
  Cenarius: 'cenarius',
  Uther: 'uther',
  Kilrogg: 'kilrogg',
  Proudmoore: 'proudmoore',
  Hyjal: 'hyjal',
  Frostwolf: 'frostwolf',
  "Ner'zhul": 'nerzhul',
  "Kil'jaeden": 'kiljaeden',
  Blackrock: 'blackrock',
  Tichondrius: 'tichondrius',
  'Silver Hand': 'silver-hand',
  Doomhammer: 'doomhammer',
  Icecrown: 'icecrown',
  Deathwing: 'deathwing',
  "Kel'Thuzad": 'kelthuzad',
  Eitrigg: 'eitrigg',
  Garona: 'garona',
  Alleria: 'alleria',
  Hellscream: 'hellscream',
  Blackhand: 'blackhand',
  Whisperwind: 'whisperwind',
  Archimonde: 'archimonde',
  Illidan: 'illidan',
  Stormreaver: 'stormreaver',
  "Mal'Ganis": 'malganis',
  Stormrage: 'stormrage',
  "Zul'jin": 'zuljin',
  Medivh: 'medivh',
  Durotan: 'durotan',
  Bloodhoof: 'bloodhoof',
  Khadgar: 'khadgar',
  Dalaran: 'dalaran',
  Elune: 'elune',
  Lothar: 'lothar',
  Arthas: 'arthas',
  Mannoroth: 'mannoroth',
  Warsong: 'warsong',
  'Shattered Hand': 'shattered-hand',
  'Bleeding Hollow': 'bleeding-hollow',
  Skullcrusher: 'skullcrusher',
  'Argent Dawn': 'argent-dawn',
  Sargeras: 'sargeras',
  Azgalor: 'azgalor',
  Magtheridon: 'magtheridon',
  Destromath: 'destromath',
  Gorgonnash: 'gorgonnash',
  Dethecus: 'dethecus',
  Spinebreaker: 'spinebreaker',
  Bonechewer: 'bonechewer',
  Dragonmaw: 'dragonmaw',
  Shadowsong: 'shadowsong',
  Silvermoon: 'silvermoon',
  Windrunner: 'windrunner',
  'Cenarion Circle': 'cenarion-circle',
  Nathrezim: 'nathrezim',
  Terenas: 'terenas',
  'Burning Blade': 'burning-blade',
  Gorefiend: 'gorefiend',
  Eredar: 'eredar',
  Shadowmoon: 'shadowmoon',
  "Lightning's Blade": 'lightnings-blade',
  Eonar: 'eonar',
  Gilneas: 'gilneas',
  Kargath: 'kargath',
  Llane: 'llane',
  'Earthen Ring': 'earthen-ring',
  'Laughing Skull': 'laughing-skull',
  'Burning Legion': 'burning-legion',
  Thunderlord: 'thunderlord',
  Malygos: 'malygos',
  Thunderhorn: 'thunderhorn',
  Aggramar: 'aggramar',
  Crushridge: 'crushridge',
  Stonemaul: 'stonemaul',
  Daggerspine: 'daggerspine',
  Stormscale: 'stormscale',
  Dunemaul: 'dunemaul',
  Boulderfist: 'boulderfist',
  Suramar: 'suramar',
  Dragonblight: 'dragonblight',
  Draenor: 'draenor',
  Uldum: 'uldum',
  Bronzebeard: 'bronzebeard',
  Feathermoon: 'feathermoon',
  Bloodscalp: 'bloodscalp',
  Darkspear: 'darkspear',
  'Azjol-Nerub': 'azjolnerub',
  Perenolde: 'perenolde',
  "Eldre'Thalas": 'eldrethalas',
  Spirestone: 'spirestone',
  'Shadow Council': 'shadow-council',
  'Scarlet Crusade': 'scarlet-crusade',
  Firetree: 'firetree',
  Frostmane: 'frostmane',
  Gurubashi: 'gurubashi',
  Smolderthorn: 'smolderthorn',
  Skywall: 'skywall',
  Runetotem: 'runetotem',
  Moonrunner: 'moonrunner',
  Detheroc: 'detheroc',
  Kalecgos: 'kalecgos',
  Ursin: 'ursin',
  'Dark Iron': 'dark-iron',
  Greymane: 'greymane',
  Wildhammer: 'wildhammer',
  Staghelm: 'staghelm',
  'Emerald Dream': 'emerald-dream',
  Maelstrom: 'maelstrom',
  'Twisting Nether': 'twisting-nether',
  "Cho'gall": 'chogall',
  "Gul'dan": 'guldan',
  "Kael'thas": 'kaelthas',
  Alexstrasza: 'alexstrasza',
  'Kirin Tor': 'kirin-tor',
  Ravencrest: 'ravencrest',
  Balnazzar: 'balnazzar',
  Azshara: 'azshara',
  Agamaggan: 'agamaggan',
  Lightninghoof: 'lightninghoof',
  Nazjatar: 'nazjatar',
  Malfurion: 'malfurion',
  Aegwynn: 'aegwynn',
  Akama: 'akama',
  Chromaggus: 'chromaggus',
  Draka: 'draka',
  "Drak'thul": 'drakthul',
  Garithos: 'garithos',
  Hakkar: 'hakkar',
  'Khaz Modan': 'khaz-modan',
  "Mug'thol": 'mugthol',
  Korgath: 'korgath',
  'Kul Tiras': 'kul-tiras',
  Malorne: 'malorne',
  Rexxar: 'rexxar',
  'Thorium Brotherhood': 'thorium-brotherhood',
  Arathor: 'arathor',
  Madoran: 'madoran',
  Trollbane: 'trollbane',
  Muradin: 'muradin',
  "Vek'nilash": 'veknilash',
  "Sen'jin": 'senjin',
  Baelgun: 'baelgun',
  Duskwood: 'duskwood',
  Zuluhed: 'zuluhed',
  'Steamwheedle Cartel': 'steamwheedle-cartel',
  Norgannon: 'norgannon',
  Thrall: 'thrall',
  Anetheron: 'anetheron',
  Turalyon: 'turalyon',
  Haomarush: 'haomarush',
  Scilla: 'scilla',
  Ysondre: 'ysondre',
  Ysera: 'ysera',
  Dentarg: 'dentarg',
  Andorhal: 'andorhal',
  Executus: 'executus',
  Dalvengyr: 'dalvengyr',
  'Black Dragonflight': 'black-dragonflight',
  'Altar of Storms': 'altar-of-storms',
  Uldaman: 'uldaman',
  'Aerie Peak': 'aerie-peak',
  Onyxia: 'onyxia',
  'Demon Soul': 'demon-soul',
  Gnomeregan: 'gnomeregan',
  Anvilmar: 'anvilmar',
  'The Venture Co': 'the-venture-co',
  Sentinels: 'sentinels',
  Jaedenar: 'jaedenar',
  Tanaris: 'tanaris',
  'Alterac Mountains': 'alterac-mountains',
  Undermine: 'undermine',
  Lethon: 'lethon',
  'Blackwing Lair': 'blackwing-lair',
  Arygos: 'arygos',
  'Echo Isles': 'echo-isles',
  'The Forgotten Coast': 'the-forgotten-coast',
  Fenris: 'fenris',
  "Anub'arak": 'anubarak',
  'Blackwater Raiders': 'blackwater-raiders',
  Vashj: 'vashj',
  Korialstrasz: 'korialstrasz',
  Misha: 'misha',
  Darrowmere: 'darrowmere',
  Ravenholdt: 'ravenholdt',
  Bladefist: 'bladefist',
  "Shu'halo": 'shuhalo',
  Winterhoof: 'winterhoof',
  'Sisters of Elune': 'sisters-of-elune',
  Maiev: 'maiev',
  Rivendare: 'rivendare',
  Nordrassil: 'nordrassil',
  Tortheldrin: 'tortheldrin',
  Cairne: 'cairne',
  "Drak'Tharon": 'draktharon',
  Antonidas: 'antonidas',
  Shandris: 'shandris',
  'Moon Guard': 'moon-guard',
  Nazgrel: 'nazgrel',
  Hydraxis: 'hydraxis',
  'Wyrmrest Accord': 'wyrmrest-accord',
  Farstriders: 'farstriders',
  'Borean Tundra': 'borean-tundra',
  "Quel'dorei": 'queldorei',
  Garrosh: 'garrosh',
  "Mok'Nathal": 'moknathal',
  Nesingwary: 'nesingwary',
  Drenden: 'drenden',
  Drakkari: 'drakkari',
  Ragnaros: 'ragnaros',
  "Quel'Thalas": 'quelthalas',
  Azuremyst: 'azuremyst',
  Auchindoun: 'auchindoun',
  Coilfang: 'coilfang',
  'Shattered Halls': 'shattered-halls',
  'Blood Furnace': 'blood-furnace',
  'The Underbog': 'the-underbog',
  Terokkar: 'terokkar',
  "Blade's Edge": 'blades-edge',
  Exodar: 'exodar',
  'Area 52': 'area-52',
  Velen: 'velen',
  'The Scryers': 'the-scryers',
  Zangarmarsh: 'zangarmarsh',
  Fizzcrank: 'fizzcrank',
  Ghostlands: 'ghostlands',
  'Grizzly Hills': 'grizzly-hills',
  Galakrond: 'galakrond',
  Dawnbringer: 'dawnbringer',
  Goldrinn: 'goldrinn',
  Nemesis: 'nemesis',
  Azralon: 'azralon',
  'Tol Barad': 'tol-barad',
  Gallywix: 'gallywix',
  Caelestrasz: 'caelestrasz',
  "Aman'Thul": 'amanthul',
  Barthilas: 'barthilas',
  Thaurissan: 'thaurissan',
  Frostmourne: 'frostmourne',
  "Khaz'goroth": 'khazgoroth',
  Dreadmaul: 'dreadmaul',
  Nagrand: 'nagrand',
  "Dath'Remar": 'dathremar',
  "Jubei'Thos": 'jubeithos',
  Gundrak: 'gundrak',
  Saurfang: 'saurfang',
} as const

export const RealmSlugs = [
  'lightbringer',
  'cenarius',
  'uther',
  'kilrogg',
  'proudmoore',
  'hyjal',
  'frostwolf',
  'nerzhul',
  'kiljaeden',
  'blackrock',
  'tichondrius',
  'silver-hand',
  'doomhammer',
  'icecrown',
  'deathwing',
  'kelthuzad',
  'eitrigg',
  'garona',
  'alleria',
  'hellscream',
  'blackhand',
  'whisperwind',
  'archimonde',
  'illidan',
  'stormreaver',
  'malganis',
  'stormrage',
  'zuljin',
  'medivh',
  'durotan',
  'bloodhoof',
  'khadgar',
  'dalaran',
  'elune',
  'lothar',
  'arthas',
  'mannoroth',
  'warsong',
  'shattered-hand',
  'bleeding-hollow',
  'skullcrusher',
  'argent-dawn',
  'sargeras',
  'azgalor',
  'magtheridon',
  'destromath',
  'gorgonnash',
  'dethecus',
  'spinebreaker',
  'bonechewer',
  'dragonmaw',
  'shadowsong',
  'silvermoon',
  'windrunner',
  'cenarion-circle',
  'nathrezim',
  'terenas',
  'burning-blade',
  'gorefiend',
  'eredar',
  'shadowmoon',
  'lightnings-blade',
  'eonar',
  'gilneas',
  'kargath',
  'llane',
  'earthen-ring',
  'laughing-skull',
  'burning-legion',
  'thunderlord',
  'malygos',
  'thunderhorn',
  'aggramar',
  'crushridge',
  'stonemaul',
  'daggerspine',
  'stormscale',
  'dunemaul',
  'boulderfist',
  'suramar',
  'dragonblight',
  'draenor',
  'uldum',
  'bronzebeard',
  'feathermoon',
  'bloodscalp',
  'darkspear',
  'azjolnerub',
  'perenolde',
  'eldrethalas',
  'spirestone',
  'shadow-council',
  'scarlet-crusade',
  'firetree',
  'frostmane',
  'gurubashi',
  'smolderthorn',
  'skywall',
  'runetotem',
  'moonrunner',
  'detheroc',
  'kalecgos',
  'ursin',
  'dark-iron',
  'greymane',
  'wildhammer',
  'staghelm',
  'emerald-dream',
  'maelstrom',
  'twisting-nether',
  'chogall',
  'guldan',
  'kaelthas',
  'alexstrasza',
  'kirin-tor',
  'ravencrest',
  'balnazzar',
  'azshara',
  'agamaggan',
  'lightninghoof',
  'nazjatar',
  'malfurion',
  'aegwynn',
  'akama',
  'chromaggus',
  'draka',
  'drakthul',
  'garithos',
  'hakkar',
  'khaz-modan',
  'mugthol',
  'korgath',
  'kul-tiras',
  'malorne',
  'rexxar',
  'thorium-brotherhood',
  'arathor',
  'madoran',
  'trollbane',
  'muradin',
  'veknilash',
  'senjin',
  'baelgun',
  'duskwood',
  'zuluhed',
  'steamwheedle-cartel',
  'norgannon',
  'thrall',
  'anetheron',
  'turalyon',
  'haomarush',
  'scilla',
  'ysondre',
  'ysera',
  'dentarg',
  'andorhal',
  'executus',
  'dalvengyr',
  'black-dragonflight',
  'altar-of-storms',
  'uldaman',
  'aerie-peak',
  'onyxia',
  'demon-soul',
  'gnomeregan',
  'anvilmar',
  'the-venture-co',
  'sentinels',
  'jaedenar',
  'tanaris',
  'alterac-mountains',
  'undermine',
  'lethon',
  'blackwing-lair',
  'arygos',
  'echo-isles',
  'the-forgotten-coast',
  'fenris',
  'anubarak',
  'blackwater-raiders',
  'vashj',
  'korialstrasz',
  'misha',
  'darrowmere',
  'ravenholdt',
  'bladefist',
  'shuhalo',
  'winterhoof',
  'sisters-of-elune',
  'maiev',
  'rivendare',
  'nordrassil',
  'tortheldrin',
  'cairne',
  'draktharon',
  'antonidas',
  'shandris',
  'moon-guard',
  'nazgrel',
  'hydraxis',
  'wyrmrest-accord',
  'farstriders',
  'borean-tundra',
  'queldorei',
  'garrosh',
  'moknathal',
  'nesingwary',
  'drenden',
  'drakkari',
  'ragnaros',
  'quelthalas',
  'azuremyst',
  'auchindoun',
  'coilfang',
  'shattered-halls',
  'blood-furnace',
  'the-underbog',
  'terokkar',
  'blades-edge',
  'exodar',
  'area-52',
  'velen',
  'the-scryers',
  'zangarmarsh',
  'fizzcrank',
  'ghostlands',
  'grizzly-hills',
  'galakrond',
  'dawnbringer',
  'goldrinn',
  'nemesis',
  'azralon',
  'tol-barad',
  'gallywix',
  'caelestrasz',
  'amanthul',
  'barthilas',
  'thaurissan',
  'frostmourne',
  'khazgoroth',
  'dreadmaul',
  'nagrand',
  'dathremar',
  'jubeithos',
  'gundrak',
  'saurfang',
] as const
export type RealmSlug = typeof RealmSlugs[number]

export type RealmName = keyof typeof RealmMap
export const RealmNames = Object.keys(RealmMap) as RealmName[]
