export enum Realm {
  'gurubashi' = 'Gurubashi',
  'skywall' = 'Skywall',
  'dalaran' = 'Dalaran',
  'garona' = 'Garona',
  'thunderlord' = 'Thunderlord',
  'dunemaul' = 'Dunemaul',
  'azjolnerub' = 'Azjol-Nerub',
  'firetree' = 'Firetree',
  'runetotem' = 'Runetotem',
  'grizzly-hills' = 'Grizzly Hills',
  'galakrond' = 'Galakrond',
  'dawnbringer' = 'Dawnbringer',
  'draenor' = 'Draenor',
  'sisters-of-elune' = 'Sisters of Elune',
  'cenarion-circle' = 'Cenarion Circle',
  'aggramar' = 'Aggramar',
  'draktharon' = 'Drak\'Tharon',
  'ravencrest' = 'Ravencrest',
  'windrunner' = 'Windrunner',
  'scarlet-crusade' = 'Scarlet Crusade',
  'stormreaver' = 'Stormreaver',
  'elune' = 'Elune',
  'shattered-hand' = 'Shattered Hand',
  'bleeding-hollow' = 'Bleeding Hollow',
  'trollbane' = 'Trollbane',
  'winterhoof' = 'Winterhoof',
  'maiev' = 'Maiev',
  'muradin' = 'Muradin',
  'veknilash' = 'Vek\'nilash',
  'senjin' = 'Sen\'jin',
  'skullcrusher' = 'Skullcrusher',
  'argent-dawn' = 'Argent Dawn',
  'destromath' = 'Destromath',
  'gorgonnash' = 'Gorgonnash',
  'dethecus' = 'Dethecus',
  'bonechewer' = 'Bonechewer',
  'dragonmaw' = 'Dragonmaw',
  'silvermoon' = 'Silvermoon',
  'terenas' = 'Terenas',
  'gorefiend' = 'Gorefiend',
  'lightnings-blade' = 'Lightning\'s Blade',
  'eonar' = 'Eonar',
  'kargath' = 'Kargath',
  'llane' = 'Llane',
  'earthen-ring' = 'Earthen Ring',
  'laughing-skull' = 'Laughing Skull',
  'burning-legion' = 'Burning Legion',
  'malygos' = 'Malygos',
  'thunderhorn' = 'Thunderhorn',
  'dragonblight' = 'Dragonblight',
  'uldum' = 'Uldum',
  'hellscream' = 'Hellscream',
  'kilrogg' = 'Kilrogg',
  'spinebreaker' = 'Spinebreaker',
  'eitrigg' = 'Eitrigg',
  'nathrezim' = 'Nathrezim',
  'feathermoon' = 'Feathermoon',
  'bloodscalp' = 'Bloodscalp',
  'rivendare' = 'Rivendare',
  'nordrassil' = 'Nordrassil',
  'cairne' = 'Cairne',
  'shandris' = 'Shandris',
  'moon-guard' = 'Moon Guard',
  'nazgrel' = 'Nazgrel',
  'hydraxis' = 'Hydraxis',
  'lightbringer' = 'Lightbringer',
  'uther' = 'Uther',
  'proudmoore' = 'Proudmoore',
  'cenarius' = 'Cenarius',
  'blackrock' = 'Blackrock',
  'silver-hand' = 'Silver Hand',
  'doomhammer' = 'Doomhammer',
  'icecrown' = 'Icecrown',
  'kelthuzad' = 'Kel\'Thuzad',
  'frostmane' = 'Frostmane',
  'madoran' = 'Madoran',
  'azuremyst' = 'Azuremyst',
  'auchindoun' = 'Auchindoun',
  'coilfang' = 'Coilfang',
  'shattered-halls' = 'Shattered Halls',
  'blood-furnace' = 'Blood Furnace',
  'the-underbog' = 'The Underbog',
  'terokkar' = 'Terokkar',
  'blades-edge' = 'Blade\'s Edge',
  'exodar' = 'Exodar',
  'area-52' = 'Area 52',
  'zangarmarsh' = 'Zangarmarsh',
  'fizzcrank' = 'Fizzcrank',
  'mannoroth' = 'Mannoroth',
  'nazjatar' = 'Nazjatar',
  'malfurion' = 'Malfurion',
  'aegwynn' = 'Aegwynn',
  'akama' = 'Akama',
  'emerald-dream' = 'Emerald Dream',
  'smolderthorn' = 'Smolderthorn',
  'blackhand' = 'Blackhand',
  'whisperwind' = 'Whisperwind',
  'archimonde' = 'Archimonde',
  'stormrage' = 'Stormrage',
  'medivh' = 'Medivh',
  'durotan' = 'Durotan',
  'bloodhoof' = 'Bloodhoof',
  'khadgar' = 'Khadgar',
  'rexxar' = 'Rexxar',
  'the-forgotten-coast' = 'The Forgotten Coast',
  'thorium-brotherhood' = 'Thorium Brotherhood',
  'fenris' = 'Fenris',
  'anubarak' = 'Anub\'arak',
  'blackwater-raiders' = 'Blackwater Raiders',
  'vashj' = 'Vashj',
  'korialstrasz' = 'Korialstrasz',
  'darrowmere' = 'Darrowmere',
  'shuhalo' = 'Shu\'halo',
  'arathor' = 'Arathor',
  'staghelm' = 'Staghelm',
  'eldrethalas' = 'Eldre\'Thalas',
  'dentarg' = 'Dentarg',
  'demon-soul' = 'Demon Soul',
  'spirestone' = 'Spirestone',
  'hyjal' = 'Hyjal',
  'lethon' = 'Lethon',
  'blackwing-lair' = 'Blackwing Lair',
  'arygos' = 'Arygos',
  'duskwood' = 'Duskwood',
  'illidan' = 'Illidan',
  'lothar' = 'Lothar',
  'sargeras' = 'Sargeras',
  'azgalor' = 'Azgalor',
  'magtheridon' = 'Magtheridon',
  'shadowmoon' = 'Shadowmoon',
  'drakkari' = 'Drakkari',
  'ragnaros' = 'Ragnaros',
  'shadow-council' = 'Shadow Council',
  'chogall' = 'Cho\'gall',
  'guldan' = 'Gul\'dan',
  'kaelthas' = 'Kael\'thas',
  'alexstrasza' = 'Alexstrasza',
  'kirin-tor' = 'Kirin Tor',
  'balnazzar' = 'Balnazzar',
  'drakthul' = 'Drak\'thul',
  'garithos' = 'Garithos',
  'hakkar' = 'Hakkar',
  'khaz-modan' = 'Khaz Modan',
  'mugthol' = 'Mug\'thol',
  'kul-tiras' = 'Kul Tiras',
  'malorne' = 'Malorne',
  'echo-isles' = 'Echo Isles',
  'zuljin' = 'Zul\'jin',
  'zuluhed' = 'Zuluhed',
  'steamwheedle-cartel' = 'Steamwheedle Cartel',
  'norgannon' = 'Norgannon',
  'thrall' = 'Thrall',
  'maelstrom' = 'Maelstrom',
  'twisting-nether' = 'Twisting Nether',
  'kalecgos' = 'Kalecgos',
  'ursin' = 'Ursin',
  'dark-iron' = 'Dark Iron',
  'wildhammer' = 'Wildhammer',
  'wyrmrest-accord' = 'Wyrmrest Accord',
  'farstriders' = 'Farstriders',
  'borean-tundra' = 'Borean Tundra',
  'queldorei' = 'Quel\'dorei',
  'garrosh' = 'Garrosh',
  'moknathal' = 'Mok\'Nathal',
  'nesingwary' = 'Nesingwary',
  'drenden' = 'Drenden',
  'azshara' = 'Azshara',
  'agamaggan' = 'Agamaggan',
  'lightninghoof' = 'Lightninghoof',
  'baelgun' = 'Baelgun',
  'anetheron' = 'Anetheron',
  'turalyon' = 'Turalyon',
  'haomarush' = 'Haomarush',
  'ysondre' = 'Ysondre',
  'ysera' = 'Ysera',
  'andorhal' = 'Andorhal',
  'executus' = 'Executus',
  'black-dragonflight' = 'Black Dragonflight',
  'altar-of-storms' = 'Altar of Storms',
  'uldaman' = 'Uldaman',
  'aerie-peak' = 'Aerie Peak',
  'onyxia' = 'Onyxia',
  'gnomeregan' = 'Gnomeregan',
  'the-venture-co' = 'The Venture Co',
  'sentinels' = 'Sentinels',
  'jaedenar' = 'Jaedenar',
  'tanaris' = 'Tanaris',
  'alterac-mountains' = 'Alterac Mountains',
  'undermine' = 'Undermine',
  'tichondrius' = 'Tichondrius',
  'bladefist' = 'Bladefist',
  'the-scryers' = 'The Scryers',
  'burning-blade' = 'Burning Blade',
  'suramar' = 'Suramar',
  'tortheldrin' = 'Tortheldrin',
  'nerzhul' = 'Ner\'zhul',
  'alleria' = 'Alleria',
  'deathwing' = 'Deathwing',
  'arthas' = 'Arthas',
  'draka' = 'Draka',
  'velen' = 'Velen',
  'frostwolf' = 'Frostwolf',
  'misha' = 'Misha',
  'moonrunner' = 'Moonrunner',
  'ghostlands' = 'Ghostlands',
  'eredar' = 'Eredar',
  'korgath' = 'Korgath',
  'detheroc' = 'Detheroc',
  'ravenholdt' = 'Ravenholdt',
  'gallywix' = 'Gallywix',
  'crushridge' = 'Crushridge',
  'daggerspine' = 'Daggerspine',
  'stormscale' = 'Stormscale',
  'boulderfist' = 'Boulderfist',
  'stonemaul' = 'Stonemaul',
  'greymane' = 'Greymane',
  'kiljaeden' = 'Kil\'jaeden',
  'perenolde' = 'Perenolde',
  'shadowsong' = 'Shadowsong',
  'malganis' = 'Mal\'Ganis',
  'darkspear' = 'Darkspear',
  'bronzebeard' = 'Bronzebeard',
  'gilneas' = 'Gilneas',
  'chromaggus' = 'Chromaggus',
  'antonidas' = 'Antonidas',
  'warsong' = 'Warsong',
  'quelthalas' = 'Quel\'Thalas',
  'dalvengyr' = 'Dalvengyr',
  'scilla' = 'Scilla',
  'anvilmar' = 'Anvilmar',
  'goldrinn' = 'Goldrinn',
  'nemesis' = 'Nemesis',
  'azralon' = 'Azralon',
  'tol-barad' = 'Tol Barad',
  'dreadmaul' = 'Dreadmaul',
  'caelestrasz' = 'Caelestrasz',
  'nagrand' = 'Nagrand',
  'amanthul' = 'Aman\'Thul',
  'barthilas' = 'Barthilas',
  'thaurissan' = 'Thaurissan',
  'dathremar' = 'Dath\'Remar',
  'frostmourne' = 'Frostmourne',
  'khazgoroth' = 'Khaz\'goroth',
  'jubeithos' = 'Jubei\'Thos',
  'gundrak' = 'Gundrak',
  'saurfang' = 'Saurfang',
}

export const RealmSlugs = [
  'gurubashi',
  'skywall',
  'dalaran',
  'garona',
  'thunderlord',
  'dunemaul',
  'azjolnerub',
  'firetree',
  'runetotem',
  'grizzly-hills',
  'galakrond',
  'dawnbringer',
  'draenor',
  'sisters-of-elune',
  'cenarion-circle',
  'aggramar',
  'draktharon',
  'ravencrest',
  'windrunner',
  'scarlet-crusade',
  'stormreaver',
  'elune',
  'shattered-hand',
  'bleeding-hollow',
  'trollbane',
  'winterhoof',
  'maiev',
  'muradin',
  'veknilash',
  'senjin',
  'skullcrusher',
  'argent-dawn',
  'destromath',
  'gorgonnash',
  'dethecus',
  'bonechewer',
  'dragonmaw',
  'silvermoon',
  'terenas',
  'gorefiend',
  'lightnings-blade',
  'eonar',
  'kargath',
  'llane',
  'earthen-ring',
  'laughing-skull',
  'burning-legion',
  'malygos',
  'thunderhorn',
  'dragonblight',
  'uldum',
  'hellscream',
  'kilrogg',
  'spinebreaker',
  'eitrigg',
  'nathrezim',
  'feathermoon',
  'bloodscalp',
  'rivendare',
  'nordrassil',
  'cairne',
  'shandris',
  'moon-guard',
  'nazgrel',
  'hydraxis',
  'lightbringer',
  'uther',
  'proudmoore',
  'cenarius',
  'blackrock',
  'silver-hand',
  'doomhammer',
  'icecrown',
  'kelthuzad',
  'frostmane',
  'madoran',
  'azuremyst',
  'auchindoun',
  'coilfang',
  'shattered-halls',
  'blood-furnace',
  'the-underbog',
  'terokkar',
  'blades-edge',
  'exodar',
  'area-52',
  'zangarmarsh',
  'fizzcrank',
  'mannoroth',
  'nazjatar',
  'malfurion',
  'aegwynn',
  'akama',
  'emerald-dream',
  'smolderthorn',
  'blackhand',
  'whisperwind',
  'archimonde',
  'stormrage',
  'medivh',
  'durotan',
  'bloodhoof',
  'khadgar',
  'rexxar',
  'the-forgotten-coast',
  'thorium-brotherhood',
  'fenris',
  'anubarak',
  'blackwater-raiders',
  'vashj',
  'korialstrasz',
  'darrowmere',
  'shuhalo',
  'arathor',
  'staghelm',
  'eldrethalas',
  'dentarg',
  'demon-soul',
  'spirestone',
  'hyjal',
  'lethon',
  'blackwing-lair',
  'arygos',
  'duskwood',
  'illidan',
  'lothar',
  'sargeras',
  'azgalor',
  'magtheridon',
  'shadowmoon',
  'drakkari',
  'ragnaros',
  'shadow-council',
  'chogall',
  'guldan',
  'kaelthas',
  'alexstrasza',
  'kirin-tor',
  'balnazzar',
  'drakthul',
  'garithos',
  'hakkar',
  'khaz-modan',
  'mugthol',
  'kul-tiras',
  'malorne',
  'echo-isles',
  'zuljin',
  'zuluhed',
  'steamwheedle-cartel',
  'norgannon',
  'thrall',
  'maelstrom',
  'twisting-nether',
  'kalecgos',
  'ursin',
  'dark-iron',
  'wildhammer',
  'wyrmrest-accord',
  'farstriders',
  'borean-tundra',
  'queldorei',
  'garrosh',
  'moknathal',
  'nesingwary',
  'drenden',
  'azshara',
  'agamaggan',
  'lightninghoof',
  'baelgun',
  'anetheron',
  'turalyon',
  'haomarush',
  'ysondre',
  'ysera',
  'andorhal',
  'executus',
  'black-dragonflight',
  'altar-of-storms',
  'uldaman',
  'aerie-peak',
  'onyxia',
  'gnomeregan',
  'the-venture-co',
  'sentinels',
  'jaedenar',
  'tanaris',
  'alterac-mountains',
  'undermine',
  'tichondrius',
  'bladefist',
  'the-scryers',
  'burning-blade',
  'suramar',
  'tortheldrin',
  'nerzhul',
  'alleria',
  'deathwing',
  'arthas',
  'draka',
  'velen',
  'frostwolf',
  'misha',
  'moonrunner',
  'ghostlands',
  'eredar',
  'korgath',
  'detheroc',
  'ravenholdt',
  'gallywix',
  'crushridge',
  'daggerspine',
  'stormscale',
  'boulderfist',
  'stonemaul',
  'greymane',
  'kiljaeden',
  'perenolde',
  'shadowsong',
  'malganis',
  'darkspear',
  'bronzebeard',
  'gilneas',
  'chromaggus',
  'antonidas',
  'warsong',
  'quelthalas',
  'dalvengyr',
  'scilla',
  'anvilmar',
  'goldrinn',
  'nemesis',
  'azralon',
  'tol-barad',
  'dreadmaul',
  'caelestrasz',
  'nagrand',
  'amanthul',
  'barthilas',
  'thaurissan',
  'dathremar',
  'frostmourne',
  'khazgoroth',
  'jubeithos',
  'gundrak',
  'saurfang',
] as const;
export type RealmSlug = typeof RealmSlugs[number];

export enum Region {
  'us' = 'US',
  'eu' = 'EU',
  'kr' = 'KR',
  'tw' = 'TW',
}

export const RegionSlugs = ['us', 'eu', 'kr', 'tw'] as const;
export type RegionSlug = typeof RegionSlugs[number];
