export const BOT_GROUP = 'bot:group:metadata'
export const BOT_SUBGROUP = 'bot:subgroup:metadata'
export const BOT_COMMAND = 'bot:command:metadata'
export const BOT_USE_GROUPS = 'bot:use-groups:metadata'
export const BOT_MODAL = 'bot:modal:metadata'
export const BOT_EVENT = 'bot:event:metadata'
export const BOT_OPTIONS = 'bot:options:metadata'
